project:
  type: website
  output-dir: docs

website:
  title: "Hemanth's World"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hemanthallamaneni
      - icon: twitter
        href: https://twitter.com/HAllamaneni
      - icon: linkedin
        href: https://www.linkedin.com/in/hemanthallamaneni/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

